### ISSUE TITLE
UnboundLocalError for UD_English-EWT

### ISSUE THREAD

**Issue by chschroeder** [pyconll/pyconll#29]
This error came up, while I was trying to load the train file from [UD_English-EWT](https://github.com/UniversalDependencies/UD_English-EWT/tree/r2.2):

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main()
  File "main.py", line 13, in main
    <redacted project-specific stuff>
    sentences = pyconll.load_from_file(train_file)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/load.py", line 41, in load_from_file
    c = Conll(f)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/unit/conll.py", line 29, in __init__
    for sentence in pyconll._parser.iter_sentences(it):
  File "/usr/local/lib/python3.5/dist-packages/pyconll/_parser.py", line 82, in iter_sentences
    sentence = _create_sentence(sent_lines, last_start, i)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/_parser.py", line 45, in _create_sentence
    sent_source, _start_line_number=start, _end_line_number=end)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/unit/sentence.py", line 87, in __init__
    line, _line_number=self.start_line_number + i)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/unit/token.py", line 343, in __init__
    Token.AV_DEPS_SEPARATOR)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/unit/token.py", line 61, in _dict_singleton_empty_map
    True, False)
  File "/usr/local/lib/python3.5/dist-packages/pyconll/unit/token.py", line 117, in _dict_empty_map_helper
    if (singleton and v is not None) or (mixed and v is None):
UnboundLocalError: local variable 'v' referenced before assignment
```
Has anyone encountered this before?

**Comment by matgrioni** [comment]
Hi Christoper,

Thanks for bringing this issue up. The problem first occurs because of token annotation 18 in the first sentence. The error occurs because of the DEPREL relation `7:obl:at`. According to the UD format, the expected pattern is `[a-z]+(:[a-z]+)?`, so the extra colon is unexpected.

I am not very familiar with this notation for the DEPREL field, and could not find anything specific on the UD_English-EWT docs. Do you have more background on this annotation pattern for DEPREL?

**Comment by chschroeder** [comment]
Hi Matias,

Thank you for looking into this. Unfortunately, i have only little experience with UD and no more background on this pattern. My use case was rather simple: I needed some annotated data in order to train and evaluate a part of speech tagger in several languages.

On the bright side, for the handful of other languages that i tried, pyconll worked flawlessly and was really easy to use.

**Comment by matgrioni** [comment]
Great! I am happy to hear.

I will try to contact the UD_English-EWT team to see if they can give more detail on their annotation and close this issue.
