### ISSUE TITLE
load file issue

### ISSUE THREAD

**Issue by RealNicolasBourbaki** [pyconll/pyconll#65]
Hi guys,

there is an issue I encountered when I used ``` pyconll.load_from_file()```:

Here is a part of ´´´conll´´´ file, it is from TüBa-D/Z, a German dependency 
```
8	.	.	_	PUNCT-$.	_|doc=T980606.31|sent_id=s99109	3	punct	_	_
```
 in the conll test file raises an error when I read in the file. The error does not occur when ```_|``` is removed in the morphology column (the one before```doc=``` and ```sent_id```)

trace back msg here:
```
Traceback (most recent call last):
  File "xxx\pos\morph_stats.py", line 144, in <module>
    this_bert_sent = next(bert_sent_gen)
  File "xxx\pos\morph_stats.py", line 105, in sentences_gen
    for this_sentence in pyconll.load_from_file(file):
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\load.py", line 48, in load_fr
om_file
    c = Conll(f)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\conll.py", line 33, in _
_init__
    for sentence in pyconll._parser.iter_sentences(it):
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\_parser.py", line 53, in iter
_sentences
    sentence = _create_sentence(sent_lines)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\_parser.py", line 24, in _cre
ate_sentence
    sentence = Sentence(sent_source)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\sentence.py", line 79, i
n __init__
    token = Token(line)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\token.py", line 539, in
__init__
    Token.AV_SEPARATOR, Token.V_DELIMITER)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\token.py", line 69, in _
dict_empty_map
    v_delimiter, _dict_empty_map_parser)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\token.py", line 242, in
_dict_empty_map_helper
    parsed = parser(v, v_delimiter)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\pyconll\unit\token.py", line 46, in _
dict_empty_map_parser
    raise ParseError(error_msg)
pyconll.exception.ParseError: Error parsing "None" properly. Please check against CoNLL format spec.
```

**Comment by matgrioni** [comment]
Hi,

I am not familiar with TüBa-D/Z, but it does not seem like it is specifically CoNLL-U from the sample. Unfortunately, pyconll only supports CoNLL-U right now (mostly because its specification is well-defined and its the most popular version). Although I have started work on a local branch to allow extension to the other CoNLL formats, I cannot say when it will be completed.

Could you provide more information on this format as well? It seems strange to me that the sent and doc id are in the morphology column and that the empty marker is still included in this column.

**Comment by RealNicolasBourbaki** [comment]
> Could you provide more information on this format as well? It seems strange to me that the sent and doc id are in the morphology column and that the empty marker is still included in this column.

Ah okay, thanks for the respond. Tüba-D/Z is in CoNLL-X format.

**Comment by matgrioni** [comment]
Closing the issue then. Thanks for bringing it up. I'll take it as more desire for supporting the various CoNLL formats out there.
